[package]
name = "subscription_external"
type = "bin"
authors = [""]
compiler_version = "0.17.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.13.1", directory="yarn-project/aztec-nr/aztec" }
